-- Optional community upgrade helpers
-- Run only if you want server-side reports and richer profile fields.

alter table if exists public.profiles add column if not exists bio text;
alter table if exists public.profiles add column if not exists avatar_url text;

create table if not exists public.comment_reports (
  id bigint generated by default as identity primary key,
  comment_id bigint,
  page_slug text,
  reason text,
  reporter_user_id uuid,
  reported_user_id uuid,
  created_at timestamptz default now()
);

alter table if exists public.comment_reports enable row level security;

drop policy if exists comment_reports_insert_public on public.comment_reports;
create policy comment_reports_insert_public
on public.comment_reports
for insert
to public
with check (true);

drop policy if exists comment_reports_select_public on public.comment_reports;
create policy comment_reports_select_public
on public.comment_reports
for select
to public
using (true);

NOTIFY pgrst, 'reload schema';
